include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display
    artifact-name: totem_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: seed_reset

  - board: nice_nano_v2
    shield: dasbob_left
  - board: nice_nano_v2
    shield: dasbob_right
  - board:  nice_nano_v2
    shield: settings_reset
    artifact-name: nicenano_reset
# there is no settingsreset (needed) for the XIAO
